*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /VTPR/LT_EXITTOP.                  " Global Data
  INCLUDE /VTPR/LT_EXITUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /VTPR/LT_EXITF00                        . " subprograms
  INCLUDE /VTPR/LT_EXITI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /VTPR/LT_EXITF...                  " Subprograms
* INCLUDE /VTPR/LT_EXITO...                  " PBO-Modules
* INCLUDE /VTPR/LT_EXITI...                  " PAI-Modules
