*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /VTPR/LT_PARAMTOP.                 " Global Data
  INCLUDE /VTPR/LT_PARAMUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /VTPR/LT_PARAMF00                       . " subprograms
  INCLUDE /VTPR/LT_PARAMI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /VTPR/LT_PARAMF...                 " Subprograms
* INCLUDE /VTPR/LT_PARAMO...                 " PBO-Modules
* INCLUDE /VTPR/LT_PARAMI...                 " PAI-Modules
